# User config
author: "James Avtges"
tagline: "James Avtges' Portfolio"
description: "Roboticist, Maker, M.S. in Robotics and current Ph.D. student at Northwestern University. My work focuses on robot learning for soft robots!"
keywords: "ROS, Robotics, Perception"
email: "jamesavtges2022@u.northwestern.edu"
resume: "https://drive.google.com/file/d/1dCCWKBgOmdYBIXdu2y2olhF5vBZs0V0l/view?usp=sharing"
linkedin: "https://www.linkedin.com/in/james-avtges/"
github: "https://github.com/javtges"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed