# User config
author: "James Avtges"
tagline: "James Avtges' Portfolio"
description: "Roboticist, Maker, aspiring Autonomy and Perception Specialist. Masters in Robotics Student at Northwestern University"
keywords: "ROS, Robotics, Perception"
email: "jamesavtges2022@u.northwestern.edu"
resume: "https://drive.google.com/file/d/13UYlvWxDJtFS7l_dk1RIdHz77r2wMzP9/view?usp=sharing"
linkedin: "https://www.linkedin.com/in/james-avtges/"
github: "https://github.com/javtges"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed